[local]
localhost

[mongodb]
mongodb.jagandevops.online

[redis]
redis.jagandevops.online

[mysql]
mysql.jagandevops.online

[rabbitmq]
rabbitmq.jagandevops.online

[catalogue]
catalogue.jagandevops.online

[user]
user.jagandevops.online

[cart]
cart.jagandevops.online

[shipping]
shipping.jagandevops.online

[payment]
payment.jagandevops.online

[frontend]
frontend.jagandevops.online